spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB-NAME}
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
  transaction:
    default-timeout: 30s

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace
      org.springframework.web.socket: DEBUG
      org.springframework.messaging: DEBUG

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

    mongodb:
      uri: mongodb://localhost:27017/chatdb
      database: chatdb

jwt:
  secret: ${JWT-SECRET}
  access-token-validity: 1800000 # 30 minutes
  refresh-token-validity: 604800000 # 7 days

kakao_api_key: ${KAKAO-MAP-API-KEY}


---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 50
