name: Deploy 자동화

on:
  workflow_run:
    workflows: ["CI 자동화"]
    types:
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.HOST }} # 서버 호스트
          port: 22
          user: ubuntu # 서버 사용자 이름 - 리눅스랑, 우분투랑 다름
          key:  ${{ secrets.PRIVATE_KEY }}# ssh 접근 권한 정보(ex:pum key)
          first_ssh: |
            echo 배포 시작
            chmod +x deploy.sh
            ./deploy.sh
            echo 배포 완료

